default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: article_growth_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: article_growth_test

production:
  <<: *default
  adapter: postgresql
  password: <%= ENV["ARTICLE_GROWTH_DATABASE_PASSWORD"] %>
